# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    name: "Build static site and run Jest tests"
    runs-on: "ubuntu-latest"
    steps:
    
    - name: "Checkout Git repository"
      uses: "actions/checkout@v3"
      
    - name: "Set up latest Node.js version"
      uses: "actions/setup-node@v3"
      with:
        node-version: "latest"
        cache: "npm"

    - name: "Install NPM dependencies"
      run: "npm ci"

    - name: "Build site statically"
      run: "npm run build --if-present"

    - name: "Run Jest tests"
      run: npm test
